### ISSUE TITLE
Unschärfen im Recover Care Wording korrigieren

### ISSUE THREAD

**Issue by MaxKannNichtCoden** [railslove/recover-backlog#100]
In der Übersicht ist noch von Tischen die Rede. Dies sollten wir in Besucher ändern. 
Beim Anlegen von Bereichen wird als Beispiel von Tisch/Theke angegeben, dafür gerne Station/Haus als Beispiel nehmen. 

Wenn es möglich wäre können wir den Speisekarten-Button bei Care/Health auch direkt immer in Hygienebestimmungen umbenennen.

**Comment by MaxKannNichtCoden** [comment]
<img width="1049" alt="Bildschirmfoto 2021-03-04 um 16 21 50" src="https://user-images.githubusercontent.com/62813999/109986098-bcc0ea00-7d05-11eb-8eb9-fdc1e0b492f5.png">
<img width="601" alt="Bildschirmfoto 2021-03-04 um 16 26 00" src="https://user-images.githubusercontent.com/62813999/109986746-51c3e300-7d06-11eb-8d29-9277e00277be.png">

**Comment by hatehashtags** [comment]
Bitte Text ändern:

aktuell          z.B. "Tisch1" oder "Theke"
neu              z.B. "Eingangsbereich" oder "Station 1"

In der Checkin-Übersicht bitte analog der recover Standard-App statt "am Tisch:" ändern in "eingecheckt:"
