### ISSUE TITLE
BUG: Information about test period differs on the same screen

### ISSUE THREAD

**Issue by hey-johnnypark** [railslove/recover-backlog#102]
![Screenshot 2021-03-05 at 13 57 30](https://user-images.githubusercontent.com/1360387/110125199-f69ff800-7dba-11eb-96b4-4313e26f2fc7.png)

**Comment by koos** [comment]
Related to #84

**Comment by koos** [comment]
Du kannst recover bis zum XYZ benutzen, dann hast du noch zwei Tage um die Bezahldaten anzugeben, ...

**Comment by bitboxer** [comment]
<img width="1013" alt="Screen Shot 2021-04-14 at 09 55 22" src="https://user-images.githubusercontent.com/56195/114674602-af851b00-9d07-11eb-8e05-518602e52317.png">
