### ISSUE TITLE
Wording falsch bei ablaufender subscription

### ISSUE THREAD

**Issue by m0ppers** [railslove/recover-backlog#105]
![image](https://user-images.githubusercontent.com/819421/111176463-a76f7980-85a9-11eb-861d-afe314039022.png)

da braucht es vermutlich neues/anderes wording.

das kommt immer, wenn im backend "block_at" gesetzt ist. block_at wird aber auch bei einer gestoppten subscription gesetzt. mindestens das "kostenlos" muss da eigentlich weg denke ich?

**Comment by hey-johnnypark** [comment]
Bei ablaufender Subscription sollte es heißen: Du nutzt aktuell eine zum x.x.x ablaufende Lizenz / Version.

Möglicherweise wird ein neues Feld benötigt.

**Comment by hatehashtags** [comment]
Textvorschlag der alle Cases erschlägt:

recover steht Dir aktuell bis dd.mm.yy in vollem Umfang zur Verfügung. Wenn Du recover nach dem dd.mm.yy weiter für Checkins nutzen möchtest, bitten wir Dich im Profil-Bereich Deine Zahlungsinformationen zu bearbeiten.
