### ISSUE TITLE
Als Account Inhaber möchte ich die Auto-Checkout Zeit meiner Gäste selbst verwalten können

### ISSUE THREAD

**Issue by MaxKannNichtCoden** [railslove/recover-backlog#107]

**Comment by MaxKannNichtCoden** [comment]
schon mit @hey-johnnypark drüber geredet. 

Ein Case wäre hier:

Bei einer Messe wäre es 
Betreiber, also wir: 10 Stunden
Standbetreiber 12 Stunden
Tische im Catering wahrscheinlich 2 Stunden
 Messebesucher wahrscheinlich die 4 Stunden

Das ermöglicht uns Recover auch für den Einsatz in wirklich großen Venues tauglich zu machen. 
Außerdem wäre dieses Feature auch präsenter für Restaurants etc. und die Quote an Karteileichen würde dadurch vermutlich sinken.

**Comment by MaxKannNichtCoden** [comment]
Kann man die 4 Stunden-Grenze für den automatischen Checkout verändern (z. B. wenn Kundentermine mal einen ganzen Tag dauern)?

Gibt mehrere Anfragen dazu mittlerweile.

**Comment by salimhb** [comment]
Das ist gerade im Admin-Backend für jeden Owner möglich: "Auto checkout minutes". Geht's hier darum, dass Betriebe den Wert selber pflegen?

**Comment by MaxKannNichtCoden** [comment]
Ja genau darum geht es. Vielleicht sogar auf Company und nicht Owner Ebene.
