### ISSUE TITLE
drucken unter iOS anschauen

### ISSUE THREAD

**Issue by m0ppers** [railslove/recover-backlog#109]
https://user-images.githubusercontent.com/819421/112356255-b4d5e380-8cce-11eb-946e-b6823d49d993.mp4

verhält sich "komisch". wurde nie mobile getestet....ggf. auch android kaputt

**Comment by rennrennrenn** [comment]
Ich guck mir das unter IOS und Android an

**Comment by rennrennrenn** [comment]
Unter Android 8.0 (Oreo) funktioniert das Drucken nicht.
Es passiert einfach nichts und man wird auf den nächsten screen weitergeleitet genau. 
Also es passiert das gleiche Verhalten wie beim Klicken auf den "weiter" Button.

**Comment by rennrennrenn** [comment]
Habe mit @MaxKannNichtCoden auf seinem aktuellen iPhone getestet und da kommen wir nicht mal so weit.
Wenn man die Datei herunterladen möchte, wird die Datei stattdessen im Browser geöffnet.

https://user-images.githubusercontent.com/32516811/114037734-884ec980-9881-11eb-8ead-54da36e574b4.mp4

Das gleich passiert, wenn man den QR-Code im für einen Tisch herunterladen möchte.

**Comment by rennrennrenn** [comment]
Was mir weiter aufgefallen ist: Die Felder um ein Passwort anzulegen (Passwort anlegen / Passwort bestätigen) unter Android wenn man in das Feld tippt soll der erste Buchstabe groß geschrieben werden.
Weiß hier jemand ob das üblich ist?

**Comment by salimhb** [comment]
> Was mir weiter aufgefallen ist: Die Felder um ein Passwort anzulegen (Passwort anlegen / Passwort bestätigen) unter Android sowie iPhone jeweils wenn man in das Feld tippt den ersten Buchstaben groß schreiben wollen.
> Weiß hier jemand ob das üblich ist?

bei mir (iPhone) ist das nicht der Fall!

**Comment by rennrennrenn** [comment]
Dann muss das am Browser liegen ich frag Max mal on wir das in nem anderen ausprobieren können.

**Comment by salimhb** [comment]
> Habe mit @MaxKannNichtCoden auf seinem aktuellen iPhone getestet und da kommen wir nicht mal so weit.
> Wenn man die Datei herunterladen möchte, wird die Datei stattdessen im Browser geöffnet.
> WhatsApp.Video.2021-04-08.at.15.42.41.mp4
> 
> Das gleich passiert, wenn man den QR-Code im für einen Tisch herunterladen möchte.

Genau, das hier ist auch ein Problem beim Browser (ist das Ecosia im Video)? Unterstützt diesen Browser überhaupt die Möglichkeit eine Datei herunterzuladen?

**Comment by rennrennrenn** [comment]
Ja genau das im Video war Ecosia ich recherchiere mal.

**Comment by rennrennrenn** [comment]
Hab das ganze gerade noch mal mit Max in Safari ausprobiert und wir konnten uns erst gar nicht registrieren:

https://user-images.githubusercontent.com/32516811/114042848-1331c300-9886-11eb-8e27-b154811966b6.mp4

@salimhb in welchem Browser hast du das denn ausprobiert?

**Comment by bitboxer** [comment]
In meinem iOS Safari kann ich mich registrieren. Habs gerade noch mal ausprobiert. Aber der Drucken-Workflow is wirklich etwas schräg. Ist die Email eventuell schon in Benutzung? Probiert mal eine andere aus.

**Comment by rennrennrenn** [comment]
@bitboxer Salim hat Max jetzt Testverbot unter iOS erteilt :D
Es funktioniert scheinbar bei allen anderen aber ich werd das ganze noch mal mit einem weiten iPhone verifizieren. Oder mal mit meinem iPad ausprobieren.

**Comment by rennrennrenn** [comment]
Also noch mal alles zusammengefasst:
Tests René:
-iPad: 
--> Safari: alles funktioniert 🎉 
--> Firefox: Download funktioniert nicht: die Textadatei wird einfach im Browser geöffnet. 
-Android 8.0:
--> Firefox: Download funktioniert. Drucken wird einfach übersprungen. 
--> Chrome: alles funktioniert 🎉 

Bodo:
-iOS:
--> Safari: Download funktioniert. DDrucken-Workflow is wirklich etwas schräg.

Salim:
-iOS:
--> Safari: alles funktioniert 🎉 

-Max:
--> Ecosia: Download funktioniert nicht, Text Datei wird im Browser geöffnet ab da kommt man dann nicht weiter.
--> Safari: Man kann nicht mal mehr auf "registrieren klicken"
