### ISSUE TITLE
Owner sollen Adressdaten ihrer Betriebe nachtragen. 

### ISSUE THREAD

**Issue by hey-johnnypark** [railslove/recover-backlog#116]
Ziel: 

Owner sollen über 2 Wege zum Nachtragen der Betriebs Adressen aufgefordert werden. Wir machen erst mal einen Soft Aufschlag, ohne Account sperren. Das kann nachgelagert enforced werden. 

1) Email an alle Owner

$(email)

@MaxKannNichtCoden @rennrennrenn habt ihr bereits mal eine E-Mail an alle Owner geschickt, falls ja wie ist der Weg? Gibt es bei Railslove ein Newsletter tool, welches ihr regelmäßig nutzt (Beispiel: Mailgun). 

2) Banner nach dem Login

$(bannerText)

a) Analog zum Payment banner eine Info mit Deep Link zum bearbeiten der Address Daten der Betriebe.  
b) Falls es mehrere Betriebe gibt, müsste eine Deep Link Liste zu jedem Betrieb angezeigt werden. 
c) Das Banner wird nur gezeigt, wenn die Betriebe noch keine Adress Daten haben. 
d) Das Banner soll so lange angezeigt werden, wie in min. einem Betrieb die Adressdaten fehlen. 

![Screenshot 2021-04-12 at 09 16 07](https://user-images.githubusercontent.com/1360387/114362868-ba0cac80-9b6f-11eb-9a64-3bf2301b2bee.png)

**Comment by rennrennrenn** [comment]
Wie benutzen MailChimp. @MaxKannNichtCoden hat darüber schon öfter Newsletter verschickt, das sollte also kein Problem sein.

**Comment by bitboxer** [comment]
Ich bräuchte noch den Bannertext, dann lege ich los damit.

**Comment by rennrennrenn** [comment]
Hmm vielleicht kann dir da @hatehashtags da ein gutes wording vorbereiten :)

**Comment by hatehashtags** [comment]
Passt das für euch?

Wichtiger Hinweis: Um im Corona-Positivfall Kontakte und Ereignisse zuordnen zu können, benötigt das Gesundheitsamt Angaben zum Standort Deiner Betriebe. Bitte trage noch bei allen Betrieben die Adresse nach. Diese ist mittlerweile eine Pflichtangabe. Vielen Dank!

**Comment by bitboxer** [comment]
<img width="1027" alt="Screen Shot 2021-04-19 at 09 32 47" src="https://user-images.githubusercontent.com/56195/115199617-af17c600-a0f3-11eb-80f8-bbb549cbe3c1.png">
