### ISSUE TITLE
Telefonnummer checken?

### ISSUE THREAD

**Issue by m0ppers** [railslove/recover-backlog#117]
in meiner "LUCA IST SCHEISSE" bubble kam jetzt häufiger "OMG DIE CHECKEN NICHTMAL DIE TELEFONNUMMER".

keine ahnung, ob man da mal ein wenig checken sollte.

Im moment ist das einfach nur ein freifeldfeld und man kann auch "hurz" eingeben.

Vielleicht gut für Akzeptanz wenigstens einen format check machen?

**Comment by bitboxer** [comment]
Das sollten wir wirklich mal einbauen.

**Comment by bitboxer** [comment]
Aber andererseits checken wir ja nicht mal die PLZ richtig im moment

**Comment by salimhb** [comment]
Und https://sms24.me/messages/luca 🤷 
Vielleicht https://www.twilio.com/voice, wenn das wirklich wichtig ist.

**Comment by m0ppers** [comment]
twilio find ich gut...hab ich schon mehrmals was mit gebaut...ist super simpel da was mit zu bauen

**Comment by bitboxer** [comment]
Okay, wir können ja fürs Erste das Eingabeformat testen mit [fix-phone](https://www.npmjs.com/package/fix-phone). Sollen wir dann zusätzlich noch eine SMS schicken? Wenn ja bräuchte ich noch ein Go und Daten zu Twilio, dann würde ich das bauen. Twilio selber hab ich auch schon einige Male eingebunden. Funktioniert super .

**Comment by salimhb** [comment]
fix-phone sieht gut aus. Das beantwortet die erste Frage von @m0ppers.
Telefonnummer Verifizierung (SMS/Voice) würde ich in einem separaten Issue diskutieren.

**Comment by bitboxer** [comment]
#25 sollten wir für die Verifizierung nutzen :)
