### ISSUE TITLE
Some users have to confirm that they have seen negative tests

### ISSUE THREAD

**Issue by MaxKannNichtCoden** [railslove/recover-backlog#121]
As a company, I would like to have the option of activating a checkbox through which users then confirm that they have presented a negative test.
To simplify the process, the user should be asked a question like: "Müssen deine Gäste dir einen negative Corona-Test vorzeigen?". Depending on the answer, the CheckBox will then be visible or not.
The guest's screen should then say something like "Ich bestätige einen negative Test vorliegen zu haben".

**Comment by MaxKannNichtCoden** [comment]
I have already spoken to @bitboxer about this

**Comment by bitboxer** [comment]
<img width="1036" alt="Screen Shot 2021-04-19 at 12 15 18" src="https://user-images.githubusercontent.com/56195/115359069-97f1da80-a1be-11eb-904b-2f0fd5a3faf6.png">

<img width="392" alt="Screen Shot 2021-04-20 at 09 06 38" src="https://user-images.githubusercontent.com/56195/115359081-9aeccb00-a1be-11eb-8eab-c9d3074b299b.png">
