### ISSUE TITLE
Bestätigung GGG

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#143]
[ ] Genesen
[ ] Geimpft
[ ] Getestet

- Foto Impfausweis
- Foto Impfnachweis
- Foto whatever-Impf-Dings
- Genesene: Nachweis Fotografieren

- Foto Testnachweis
- Foto TestQR

**Comment by koos** [comment]
Sport bis zu 20 personen unter freiem Himmel brauchen keinen 3-Gs-Nachweis. Checkbox also nicht verpflichtend oder wie machen wir das? @bitboxer

**Comment by bitboxer** [comment]
Und wie sieht der wirt das dann?

**Comment by bitboxer** [comment]
Closed by https://github.com/railslove/rcvr-app/pull/193
