### ISSUE TITLE
Finally we need some more checkboxes again

### ISSUE THREAD

**Issue by MaxKannNichtCoden** [railslove/recover-backlog#144]

**Comment by MaxKannNichtCoden** [comment]
It seems that Recover Care customers also need to be able to select the checkboxes in the screenshot below soon. 
However, I think that you should also be able to check in if you have not selected all 3.

@bitboxer 

<img width="607" alt="Bildschirmfoto 2021-05-19 um 11 19 22" src="https://user-images.githubusercontent.com/62813999/118788882-83bffc80-b894-11eb-988b-f4c1285213ca.png">

**Comment by koos** [comment]
Der genaue Wortlaut für 3 Checkboxen ist (davon ist min. 1 mandatory):


- [ ] Getestet: Ich bestätige ein negatives, nicht älter als 48 Stunden zurückliegendes Testergebnis vorliegen zu haben und dieses im Prüfall vorweisen zu können. 
- [ ] Genesen: Ich bestätige eine Dokumentation über meine Genesung von einer Corona-Erkrankung vorweisen zu können und diese im Prüffall vorweisen zu können. 
- [ ] Geimpft: Ich bestätige eine Dokumentation ( Impfpass) über meine Impfung gegen eine Infektion mit dem Coronavirus vorweisen zu können und diese im Prüffall vorweisen zu können.

**Comment by bitboxer** [comment]
<img width="460" alt="Screen Shot 2021-05-19 at 17 54 06" src="https://user-images.githubusercontent.com/56195/118844451-4165e200-b8cb-11eb-8948-36afd5f9c673.png">

**Comment by koos** [comment]
Hi. @bitboxer hast du das hier berücksichtigt? #143 - bzw. dort gab es noch eine Frage.
Wer kann denn das Feature hier reviewen und deployen - es wäre super wenn wir das morgen online haben, wg. Wiedereröffnung. @salimhb @hey-johnnypark @bonflintstone

**Comment by bitboxer** [comment]
Das hab ich berücksichtigt. Die checkbox kann optional aktiviert werden. Und dann steht das im datenexport, was die Person angeklickt hat.
