### ISSUE TITLE
As a bar owner I can download the AVV during the registration process

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#15]
Als Gastronom kann ich mir eine Auftragsdatenvereinbarung bei der Registirerung ansehen. Nehmen sie bitten Kenntniss von unserer Datenschutzerklärung diese finden sie hier und sie finden die Auftragsverarbeitungsvereinbarung.

Im ersten Regestirerungsschritt direkt unter den Verträgen.

**Comment by koos** [comment]
similar to #2

**Comment by koos** [comment]
Aktuellen AVV noch mal hochladen @koos

**Comment by hey-johnnypark** [comment]
Hi @koos , 

1. wo kann ich das AVV Dokument finden? 
2. Ich nehm an das die hier verlinkt werden sollen?

![Screenshot 2020-12-17 at 17 13 35](https://user-images.githubusercontent.com/1360387/102520176-507e0500-408b-11eb-9bab-cef0059db0fe.png)

**Comment by rennrennrenn** [comment]
@tatjanala  Hier brauchen wir noch den AVV.

**Comment by tatjanala** [comment]
Hier sind die drei verschiedenen Versionen, einmal für recover, care & health.
[AVV_recover.pdf](https://github.com/railslove/recover-backlog/files/6049515/AVV_recover.pdf)
[AVV_recover.heath.pdf](https://github.com/railslove/recover-backlog/files/6049529/AVV_recover.heath.pdf)
[2021_AVV_recover.care.pdf](https://github.com/railslove/recover-backlog/files/6049476/2021_AVV_recover.care.pdf)
