### ISSUE TITLE
Affiliate Overview on a company basis - Backend

### ISSUE THREAD

**Issue by KiraRL** [railslove/recover-backlog#174]
As an admin I would like to have access to a list that contains affiliates not on an owner but a company basis. Licenses are billed according to the number of companies, owners would distort the number of licenses that have to be billed each month. 
The new view should display not only Company, owner, address and ID but also the date at wich the affiliate Program ends for each company. That way we can plan our billing periods accurately and transparently. 
The overview would be similar to what one sees when they click on the owner numbers in the screenshot below. Maybe we could access the desired company view by clicking on the company figures. 
Please let me know if anything needs to be cleared up.
<img width="1045" alt="Bildschirmfoto 2021-08-05 um 15 44 18" src="https://user-images.githubusercontent.com/85234407/128361127-4f336d88-e3e7-462a-9490-98870c2953d6.png">
<img width="1177" alt="Bildschirmfoto 2021-08-11 um 11 58 43" src="https://user-images.githubusercontent.com/85234407/129010198-da67d856-4aa8-47b6-aa91-7bcbd6ccadd6.png">

**Comment by bitboxer** [comment]
Default sort: inserted at, newest first.
