### ISSUE TITLE
As a owner I want to edit my personal profile data

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#19]

**Comment by m0ppers** [comment]
als betrieb kann man nix machen. namensänderung, adresse etc.

**Comment by m0ppers** [comment]
/business/profile

**Comment by bitboxer** [comment]
<img width="1038" alt="Screen Shot 2021-04-13 at 15 50 06" src="https://user-images.githubusercontent.com/56195/114565808-ee689180-9c71-11eb-820c-dec6909e3abb.png">

<img width="519" alt="Screen Shot 2021-04-13 at 15 51 27" src="https://user-images.githubusercontent.com/56195/114565825-f1fc1880-9c71-11eb-985a-137ab8865e16.png">
