### ISSUE TITLE
As a guest I want to be notified after a ticket was labeled

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#20]
@bonflintstone

**Comment by bonflintstone** [comment]
I do not think we will be building this since right now this is on the authority of the Gesundheitsamt. This was relevant for the previous plan of having rcvr more independent/ more akin to the corona app, but I do not think we will be going this route.

**Comment by koos** [comment]
I am not sure - I would like to discus that. This could be an USP of recover: imagine we also could read the official QR Code of the health authority, we could notify other users about it. Let's discuss some opportunities for recover before rejecting an idea too early.
