### ISSUE TITLE
Autocomplete für Felder verbessern

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#21]
@bonflintstone 
@timomeh Wir nutzen dafür auto-complete="street-address", ich glaube es gibt keins für Straße und Ort

**Comment by m0ppers** [comment]
datenfelder aufteilen (strasse in separate textzeile bspw.), damit der browser die textfelder möglichst weit autocompleten kann, damit man weniger tippen muss

**Comment by MaxKannNichtCoden** [comment]
<img width="637" alt="Bildschirmfoto 2021-03-13 um 16 17 00" src="https://user-images.githubusercontent.com/62813999/111034856-ca6a2400-8417-11eb-8f96-ea1aa9feb5d1.png">

Hier auch noch eine Anfrage dazu. Könnte wirklich hilfreich sein die Änderung weil ansonsten vermutlich auch viele Menschen vergessen ihre Daten kompöett einzugeben.

**Comment by hey-johnnypark** [comment]
@MaxKannNichtCoden Bezüglich des letzten Comments. Ich denke das ist das was in der E-Mail gemeint ist oder? 

<img width="479" alt="Screenshot 2021-03-13 at 19 22 42" src="https://user-images.githubusercontent.com/1360387/111041711-7ec47400-8431-11eb-9272-bc3c5f166882.png">

**Comment by hey-johnnypark** [comment]
Hi Again,

bezüglich des Autocomplete. 

Es ist nicht möglich, die gesamten Adressdaten über Auto Complete in ein Feld zu schreiben. Der sauberste Weg ist der den @m0ppers beschrieben hat. 

<img width="439" alt="Screenshot 2021-03-13 at 19 33 48" src="https://user-images.githubusercontent.com/1360387/111042011-0bbbfd00-8433-11eb-8cc2-957db1bf67b7.png">

Hier müssten wir dann überlegen, wie wir das Format in das eine Feld schreiben, denn im Backend gibt es nur ein Feld. 

Was denkst du @MaxKannNichtCoden 

Du kannst dir das live hier anschauen: https://rcvr-app-cr3ifbt5h-railslove.vercel.app/

**Comment by bitboxer** [comment]
Die Liste an Autocomplete-Attributen gibt es übrigens [hier](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).

Einige Apps haben zusätzlich noch im Straßen-Feld ein Google-Maps-Search aktiv. Wenn man anfängt den Straßennamen einzugeben, poppt dann eine Vorschlagsliste auf. Falls die Nutzerin daraus was auswählt, wird das dann in die entsprechenden Felder eingefügt. So hat man dann einerseits ein funktionierendes Autocomplete und zusätzlich noch eine Hilfe beim Eingeben der Adresse.

**Comment by bonflintstone** [comment]
Ich denke google maps oder ähnliche services sind aus Datenschutzgründen nicht optimal. Die Adress Felder aufteilen und dann fürs Backend einfach zusammen joinen find ich nen guten Ansatz, ich denke da brauchen wir nicht mehr Felder

**Comment by bitboxer** [comment]
Mit [#6](https://github.com/railslove/recover-backlog/issues/6) gibt es auch die Möglichkeit, Daten nachträglich zu editieren. Da wird eventuell das Zusammenführen etwas komplexer, da es zum editieren wieder auseinander geschnitten werden muss.

**Comment by salimhb** [comment]
> Ich denke google maps oder ähnliche services sind aus Datenschutzgründen nicht optimal. 

👍 

> Die Adress Felder aufteilen und dann fürs Backend einfach zusammen joinen find ich nen guten Ansatz, ich denke da brauchen wir nicht mehr Felder

Das ist schon der Fall. Alle Felder (Name, Tel, Adresse) werden schon als CSV joined, encrypted, und in das Backend als ein Feld gespeichert. Wir mussen dann in DataRequests aufpassen, wie wir die Felder nach Decryption wieder splitten.

**Comment by bonflintstone** [comment]
> Mit [#6](https://github.com/railslove/recover-backlog/issues/6) gibt es auch die Möglichkeit, Daten nachträglich zu editieren. Da wird eventuell das Zusammenführen etwas komplexer, da es zum editieren wieder auseinander geschnitten werden muss.

Ich bin mir recht sicher, dass wir die Daten nicht entschlüsseln um die zu editieren, wir "überschreiben" die daten einfach mit neuen Daten. Entschlüsseln könnte der Endnutzer die Daten ja auch gar nicht.

Ich denke wir sollte die Daten einfach unwiderbringlich verheiraten und auch die CSV nicht ändern. Im frontend haben wir die 3 Felder und im verschlüsselten json steht dann `${street}, ${zip} ${city}`. Ich denke das ist _gut genug_:tm:

**Comment by bitboxer** [comment]
Der PR hat nun PLZ und Ort als separate Felder. Ein kleiner Punkt: falls die Nutzerin schon Daten eingegeben hat, bleiben die weiter im Adress-Feld, das müsste sie dann manuell korrigieren, falls notwendig.

**Comment by bitboxer** [comment]
Schaut euch das ganze gerne an in der Staging-Umgebung: https://rcvr-app-h1d54tt9p-railslove.vercel.app/
