### ISSUE TITLE
Take over the address when checking in with several people

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#34]

**Comment by koos** [comment]
@koos @p3nny besser beschreiben

**Comment by devchris** [comment]
Do we want to only take over the address, or should we also take over the phone number?

**Comment by devchris** [comment]
Since no one replied, I made the decision to what I believe would make the most sense. Taking over the phone number as well. Can't think of a real world scenario where you want to copy the address but not the phone number 🤷‍♂️
