### ISSUE TITLE
Prefill Guest Info from URL Parameter on QR Scanner Page

### ISSUE THREAD

**Issue by salimhb** [railslove/recover-backlog#44]
Currently it's possible for other services to integrate with Recover and provide existing guest information to the checkin page by added parameters to the Checkin URL. Ex: 
```
https://rcvr.app/checkin?a=a034a62c-7c7a-4646-a58e-a11cdbc75393&k=x8vR6OG%2BHD%2BbD0PVIR%2FIqVWluAD7tyTj5H9sOplUSgs%3D&name=Salim&phone=12345&address=Street
```
This requires that the service integrating with Recover implements a QR-Scanner to read the URL from the QR-Code and append the guest parameters to it.

Recover already implements a QR-Scanner at https://rcvr.app/qr. To make it easier for 3rd parties to integrate Recover, we want to support the same guest parameters at the scanner page ex:
```
https://rcvr.app/qr?name=Salim&phone=12345&address=Street
```

**Comment by hey-johnnypark** [comment]
I encounter a weird behaviour that the /qr page is loaded twice (that is an inconsistent behaviour). 

![Screenshot 2020-12-17 at 18 30 17](https://user-images.githubusercontent.com/1360387/102528055-edde3680-4095-11eb-95ea-542e4db1a23c.png)

I try my best to fix this but maybe @salimhb  you have an idea.

**Comment by hey-johnnypark** [comment]
I think I found the issue. https://github.com/vercel/next.js/issues/10521 I will try to use a React effect in order to fetch the params.

**Comment by hey-johnnypark** [comment]
1) Check with all params
http://localhost:3001/qr?name=Andi&phone=12345&address=FooStreet

![Screenshot 2020-12-17 at 18 56 52](https://user-images.githubusercontent.com/1360387/102531028-a3f74f80-4099-11eb-948b-ecdb5e5eed55.png)

2) Check with no params
http://localhost:3001/qr

![Screenshot 2020-12-17 at 18 57 47](https://user-images.githubusercontent.com/1360387/102531139-c38e7800-4099-11eb-9ddc-e59d858eefde.png)
