### ISSUE TITLE
As a user I want to see the correct pricing information on "Mein Profil"

### ISSUE THREAD

**Issue by tatjanala** [railslove/recover-backlog#48]
![image001 (3)](https://user-images.githubusercontent.com/979631/101332549-bb526380-3875-11eb-81d1-26dc63237f13.png)

**Comment by tatjanala** [comment]
New text: 
Sie können recover health noch bis zum xx.xx.xxxx kostenlos testen.

Sie können recover 14 Tage lang kostenlos testen.  Danach kostet die Mitgliedschaft für alle Krankenhäuser mit einer Größe bis 199 Betten 199€ pro Monat, für alle Krankenhäuser mit einer Größe von 200 bis 499 Betten 349€ pro Monat und
für alle Krankenhäuser mit einer Größe von 500 Betten 449€ pro Monat bei einer jeweiligen 
Mindestlaufzeit von 6 Monaten.

Bei Fragen zum Pricing können Sie sich jederzeit bei unserem Support unter team@recoverapp.com melden.

Link: Jetzt recover health abonnieren (mailto: team@recoverapp.com)

![Group](https://user-images.githubusercontent.com/979631/101343893-f4de9b00-3884-11eb-97f0-6ab9f8605fb9.png)

**Comment by m0ppers** [comment]
![image](https://user-images.githubusercontent.com/819421/101382159-eb225b00-38b7-11eb-82a3-79944e07c384.png)

I changed "kannst" vs "darfst" across all environments so changes are minimal. If this is not wanted please ping me.

**Comment by m0ppers** [comment]
![image](https://user-images.githubusercontent.com/819421/101382465-46ece400-38b8-11eb-9578-04f7ceef83b9.png)

kannst vs. darfst in recover (care also uses kannst now)
