### ISSUE TITLE
As a user I don't want to pay by credit card. 

### ISSUE THREAD

**Issue by tatjanala** [railslove/recover-backlog#49]
![Bildschirmfoto 2020-12-07 um 10 15 53](https://user-images.githubusercontent.com/979631/101333322-c5c12d00-3876-11eb-8951-1f544f099ae4.png)

**Comment by tatjanala** [comment]
Stripe integration can be deleted.

**Comment by P3nny** [comment]
Wenn sie recover weiter nutzen möchten, schreiben sie uns eine E-Mail und auf den Button:
"E-Mail schreiben"

**Comment by salimhb** [comment]
Maybe this is not an issue if we do #9 ?
