### ISSUE TITLE
Als Admin-Nutzer möchte ich Whitelabel-Konfigurationen in rails admin anlegen und bearbeiten können.

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#5]
- [ ] Im /admin möchte ich alle Whitelabel-Konfigurationen sehen

- [ ] In /admin kann ich Whitelabels anpassen (Farben, Logos, Texte)

**Comment by koos** [comment]
@salimhb: Ist whitelabeling auch für die Checkins-Seite?

**Comment by koos** [comment]
@endverbraucher Begonnen: railslove/rcvr-api: https://github.com/railslove/rcvr-api/pull/42

**Comment by endverbraucher** [comment]
Im Backend in rails_admin können whitelabels angelegt und bearbeitet werden. Diese müssen noch über die API zur Verfügung gestellt werden.

Als Whitelabel werden in der App dann die Checkin-Seite und "Meine Checkins" angepasst. Dafür liegt in der App aktuell eine statische Konfigurations, die man dann durch den API-Aufruf austauschen sollte.

Das Whitelabeling ist für den ersten Schritt nur für die verschiedenen Frontends (Care, Health, Fresenius und Rcvr gedacht.) Könnte man aber später zu einem Premium-Feature erweitern.
