### ISSUE TITLE
Als Gast moechte ich meine daten bearbeiten koennen auch wenn ich die schonmal gespeichert habe

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#6]
- Möglichkeit Typos fixen können, wenn sie mir bei einem zweiten Besuch auffallen
- Nicht rückwirkend, aber ab diesem Besuch

Ignore: Vielleicht sind vorausgefuellte felder da nicer, haben da feedback von kunden bekommen

**Comment by hey-johnnypark** [comment]
Hi @koos ,

Ich denke die Daten zu bearbeiten macht genau hier Sinn. Kannst du kurz drüber schauen ob das so ok ist? Cheers!

<img width="499" alt="Screenshot 2020-12-18 at 09 09 07" src="https://user-images.githubusercontent.com/1360387/102596245-cbd5ca00-4110-11eb-9766-885b1abf59d5.png">

<img width="428" alt="Screenshot 2020-12-18 at 09 09 30" src="https://user-images.githubusercontent.com/1360387/102596257-cf695100-4110-11eb-8c81-85c5e23d34f1.png">

**Comment by koos** [comment]
Can you adjust the padding/margin between "Deine Daten Ändern" and "Name"

**Comment by tatjanala** [comment]
Als Besucher in einer Pflegeeinrichtung/ einem Krankenhaus möchte ich die Möglichkeit haben nach dem Check-out, bzw. bei meinem nächsten Besuch/Check-in den Besuchernamen zu bearbeiten bzw. einen neuen Besuchernamen anzugeben.

**Comment by hey-johnnypark** [comment]
I ran into a problem. 

Ticket.id is of type :uuid. This causes inconsistent behaviour in papertrail:

https://github.com/paper-trail-gem/paper_trail/issues/363

I try to work my way around this with the solution suggsted.

**Comment by bitboxer** [comment]
Der Frontend-Teil muss noch gemerged werden, bevor es hier geschlossen werden kann 😉
