### ISSUE TITLE
Error when removing menu pdf (500 from server)

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#8]
When a business owner is logged in and on the company index page, she can edit a company and either upload a pdf or enter a link to the restaurant's menu.
There is a button to delete a previously uploaded PDF. If she clicks the delete button and then clicks save, an error occurs (see screenshot).

![Screen Shot 2020-11-03 at 2 49 10 PM](https://user-images.githubusercontent.com/1375839/97993025-d0a22100-1de3-11eb-8583-f0f3adc80e47.png)
![Screen Shot 2020-11-03 at 2 49 21 PM](https://user-images.githubusercontent.com/1375839/97993032-d26be480-1de3-11eb-9942-6ac47b1dbd61.png)

**Comment by m0ppers** [comment]
needs more context. where do I have to click? no idea (yet) where this menu.pdf is supposed to be found

**Comment by salimhb** [comment]
> needs more context. where do I have to click? no idea (yet) where this menu.pdf is supposed to be found

I updated the description.
