### ISSUE TITLE
Logo on the Checkin-Screen

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#85]
Due to the corporation with government institutions there is a small whitelabel request:

**As an Admin:**
As an Admin I can upload an Logo to an given afiliate deal and when the Business owner uses this affiliate link the logo is shown for the user.

**As a user:**
I want to check in with recover
So I can drink a beer

Given that the business owner uses recover
And I have a smartphone
And I there is a QR code on the table
When I scan the QR code

[Scenario 1: my data are already stored]
Then I'll see the checkin page with a logo on the top right corner beside the recover logo
And I'm checked in

[Scenario 2: my data aren't already stored]
Then i'll have to type in my data on a screen with the logo of the government client beside the recover logo
And If I click "checkin" then I'll be redirected to the checkin page
And I see a logo on the top right corner beside the recover logo
And I'm checked in

Scenario 2: 
![IMG_5843](https://user-images.githubusercontent.com/8343/108037222-9169aa00-7039-11eb-880e-145232e1ade8.jpg)

Scenario 1 & 2:
![IMG_5843](https://user-images.githubusercontent.com/8343/108037263-a0e8f300-7039-11eb-8d1b-d449b4012b57.jpg)

**Comment by hey-johnnypark** [comment]
Zusätzlich One Pager notwendig über die Möglichkeiten als Affiliate Sponsor. @rennrennrenn

**Comment by hey-johnnypark** [comment]
@MaxKannNichtCoden @rennrennrenn könnt ihr bitte die Designs nochmal anhängen bitte.

**Comment by MaxKannNichtCoden** [comment]
https://www.figma.com/file/uCR8YoxoTUM3o3kSaiUPFv/Onboarding?node-id=209%3A2
FigmaFigma


https://www.figma.com/file/AZdH3y203EgkzEPCsCqdRD/Web-App?node-id=849%3A0

**Comment by bitboxer** [comment]
~~Wenn ich den Code richtig sehe, gibt es gerade keine Verbindung zwischen einer `Company` und einem `Affiliate`. Jetzt stellt sich mir gerade die Frage, wie ich das Affiliate Logo in der jeweiligen `Company` darstellen kann. Soll hier jetzt eine Verbindung zwischen beiden angelegt werden?~~

Korrektur: habe die Verbindung gefunden. Ist ein String der den Affiliate code enthält. Eventuell sollte das mal auf eine ID geändert werden. Wenn ich den Code ändere im Backend sind sonst sämtliche Verknüpfungen weg?
