### ISSUE TITLE
User kann sich nicht einloggen

### ISSUE THREAD

**Issue by koos** [railslove/recover-backlog#87]
Max In Verbindung mit der Verifikationsmails scheint es zu einem Fehler zu kommen

2:47 PM
Und man kann sich nicht mehr einloggen

Max Ich kann es halt schwer definieren ;D
3:01 PM
Also die meinte sie kann sich einfach mit ihren Daten nicht einloggen
3:01 PM
wann immer sie PW und Username eingibt wird sie dann nicht weitergeleitet

**Comment by rennrennrenn** [comment]
Weitere Besprechung mit @MaxKannNichtCoden:
User registriert sich. Erhält Bestätigungsmail mit Link.
Nach dem klicken auf den Link funktioniert der Login nicht mehr.
Disher 3 x mal bei recover Health vorgekommen.

**Comment by hey-johnnypark** [comment]
@rennrennrenn und ich haben zusammen versucht, das Problem nachzustellen. 

a) Lokal und b) auf https://health.rcvr.app

In beiden Fällen konnten wir das Problem nicht nachstellen. Wir haben einen Bug gefunden, der aber wahrscheinlich nichts mit dem Problem zu tun hat: 

Das ganz haben wir hier dokumentiert https://github.com/railslove/recover-backlog/issues/92

Ich schlage vor, dass wir a) Zugang zu den Logs bekommen @bonflintstone kannst du hier helfen? und b) mal direkt mit einem betroffenen Kunden sprechen (am besten über screensharing).

**Comment by rennrennrenn** [comment]
Mit @MaxKannNichtCoden sprechen um User zu befragen.

**Comment by hey-johnnypark** [comment]
Hat in einem anderen Browser funktioniert. Kann geschlossen werden.
