### ISSUE TITLE
Abfrage Kundendaten UX-Optimierungen Ausbaustufe 1

### ISSUE THREAD

**Issue by JanaFranzen** [railslove/recover-backlog#89]
Farbliche Unterscheidung zwischen Daten für Plausibilitätsprüfung/Ordnungsamt und Daten für das  Gesundheitsamt.
Auf Detailseite/Tabelle mit Kundendaten: Kennzeichnung der Kontaktdaten der letzten 2 Stunden und ältere Kontaktdaten

https://www.figma.com/file/eorCpdS6pkdjT3sKNBQac3/Recover-UX?node-id=0%3A1

![Ausbaustufe 1](https://user-images.githubusercontent.com/78360490/108219398-fd313d00-7135-11eb-846a-f5e70296243b.png)
![Ausbaustufe 1 Detail](https://user-images.githubusercontent.com/78360490/108219412-015d5a80-7136-11eb-834a-7d21f7dbf7ca.png)

**Comment by bitboxer** [comment]
Result:

![Screen Shot 2021-04-16 at 11 52 06-fullpage](https://user-images.githubusercontent.com/56195/114850445-0e6a9300-9de1-11eb-9bdf-23fc307d691c.png)

![Screen Shot 2021-04-16 at 11 52 16-fullpage](https://user-images.githubusercontent.com/56195/114850454-10cced00-9de1-11eb-80e0-b01e0fab11ac.png)
