### ISSUE TITLE
Links in E-Mails leiten auf falsche Domain

### ISSUE THREAD

**Issue by hey-johnnypark** [railslove/recover-backlog#92]
PROBLEM:

In den folgenden beiden Fällen wird der Benutzer aus Recover Health falsch auf Recover App weitergeleitet. 

1) Kontoregistrierung

2) Password Vergessen

<img width="713" alt="Screenshot 2021-02-23 at 19 04 34" src="https://user-images.githubusercontent.com/1360387/108894270-fad55400-7609-11eb-91d6-8e8efbdd3c85.png">

<img width="780" alt="Screenshot 2021-02-23 at 19 04 55" src="https://user-images.githubusercontent.com/1360387/108894311-0759ac80-760a-11eb-941d-dfa04cc8f903.png">

<img width="715" alt="Screenshot 2021-02-23 at 19 05 35" src="https://user-images.githubusercontent.com/1360387/108894432-2e17e300-760a-11eb-9afe-56139de5cd92.png">

<img width="735" alt="Screenshot 2021-02-23 at 19 05 47" src="https://user-images.githubusercontent.com/1360387/108894430-2ce6b600-760a-11eb-9fc9-cce51b7850a1.png">

**Comment by bitboxer** [comment]
Bei Kontoregistrierung hats schon korrekt funktioniert für mich. Beim Passwort Rest kommt jetzt gleich ein PR 😉
