### ISSUE TITLE
Link "NRW" auf "Böblingen" ändern.

### ISSUE THREAD

**Issue by rennrennrenn** [railslove/recover-backlog#93]
Mail Oliver Messer:
Text bei „Account erstellen“ verweist (nur) auf NRW. Kann das für die Version Böblingen (BB) geändert werden?
![image](https://user-images.githubusercontent.com/32516811/109035192-ae048280-76c8-11eb-80bd-cf458688c23d.png)

**Comment by hey-johnnypark** [comment]
@silkekanes @rennrennrenn Das sieht jetzt so aus:

<img width="520" alt="Screenshot 2021-03-05 at 19 29 39" src="https://user-images.githubusercontent.com/1360387/110164350-236b0400-7de9-11eb-8a66-2068c9207627.png">

Ich denke das Ticket kann geschlossen werden.

**Comment by hey-johnnypark** [comment]
@rennrennrenn @silkekanes  Das Ticket ann geschlossen werde richtig?
