### ISSUE TITLE
wording generalisieren => Weniger auf Gastros bezogene Wortwahl

### ISSUE THREAD

**Issue by rennrennrenn** [railslove/recover-backlog#95]
![image](https://user-images.githubusercontent.com/32516811/109130473-10559580-7752-11eb-9d78-2a16fae31945.png)
![image](https://user-images.githubusercontent.com/32516811/109130499-15b2e000-7752-11eb-9a5b-54480ca959c9.png)

**Comment by hatehashtags** [comment]
[Uploading 2021-03 Texte.docx…]()

**Comment by hatehashtags** [comment]
Hoffentlich verständlich: Habe Screenshots gemacht und alle Änderungen darunter geschrieben.Es bleibt erstmal beim Du, daher alle "Sie" entfernt. Gastro rausgenommen und allgemeinen Fokus. Auch den Text mit der fehlenden Subskription angepasst.
