### ISSUE TITLE
SEPA - the final ticket

### ISSUE THREAD

**Issue by m0ppers** [railslove/recover-backlog#96]
Feedback when subscription is being created (request takes quite a while). Use some kind of feedback (animated button etc).

- Somehow after clicking back and forth in the UI you cannot change from credit card to sepa and vice versa

In the admin ui on the profile page with active subscription:
- Zahlungsmethode ändern instead Rechnungsdaten ändern (does not fit for sepa otherwise)
- Remove "Rechnungen" completely

- Remove feature flag sepa debit and push it to health and care as well

**Comment by hey-johnnypark** [comment]
@m0ppers There is a loading component which is been used through out the app (the three green jumping dots)

`import { Loading } from '~ui/blocks/Loading'`

I found it quite useful in another ticket :)
