### ISSUE TITLE
Text Sormas formulieren

### ISSUE THREAD

**Issue by rennrennrenn** [railslove/recover-backlog#98]
Mail Oliver Messer:
Die SORMAS Schnittstelle bzw. der Export für SORMAS ist fertig, oder? Kann ich das in den Text mit aufnehmen? So als „Seitenhieb“ auf die LUCA-App?

Ist noch in der Designphase.

**Comment by hatehashtags** [comment]
Text zur Kommunikation:

recover ist Teil der Initiative "Wir für Digitalisierung", die allen Gesundheitsämtern über ein standardisiertes offenes Gateway digitale Kontaktdaten per Knopfdruck verfügbar macht. Dieses Gateway liefert angefragte Kontaktlisten im für SORMAS passenden Format aus.

**Comment by hey-johnnypark** [comment]
@rennrennrenn Können wir dieses Ticket schließen?

**Comment by rennrennrenn** [comment]
Schon passiert danke dir Andi :)
